/* tslint:disable */
/* eslint-disable */
/**
 * Screenrights Permissions API
 * The Screenrights Permissions API documentation.
 *
 * The version of the OpenAPI document: 0.0.0-dev.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateProfileDto
 */
export interface CreateProfileDto {
    /**
     * 
     * @type {string}
     * @memberof CreateProfileDto
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof CreateProfileDto
     */
    middleName?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateProfileDto
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof CreateProfileDto
     */
    imageUri?: string;
}

