/* tslint:disable */
/* eslint-disable */
/**
 * Screenrights Permissions API
 * The Screenrights Permissions API documentation.
 *
 * The version of the OpenAPI document: 0.0.0-dev.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { PaginationMeta } from './pagination-meta';
// May contain unused imports in some cases
// @ts-ignore
import { User } from './user';

/**
 * 
 * @export
 * @interface PaginatedUsersDto
 */
export interface PaginatedUsersDto {
    /**
     * 
     * @type {Array<User>}
     * @memberof PaginatedUsersDto
     */
    items: Array<User>;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof PaginatedUsersDto
     */
    meta: PaginationMeta;
}

