/* tslint:disable */
/* eslint-disable */
/**
 * Screenrights Permissions API
 * The Screenrights Permissions API documentation.
 *
 * The version of the OpenAPI document: 0.0.0-dev.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PaginationMeta
 */
export interface PaginationMeta {
    /**
     * 
     * @type {number}
     * @memberof PaginationMeta
     */
    totalItems: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationMeta
     */
    itemCount: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationMeta
     */
    itemsPerPage: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationMeta
     */
    totalPages: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationMeta
     */
    currentPage: number;
}

