/* tslint:disable */
/* eslint-disable */
/**
 * Screenrights Permissions API
 * The Screenrights Permissions API documentation.
 *
 * The version of the OpenAPI document: 0.0.0-dev.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const PermissionEnum = {
    AddWorkspace: 'add-workspace',
    ChangeNameOfLegalEntity: 'change-name-of-legal-entity',
    DeactivateClients: 'deactivate-clients',
    DeactivateUser: 'deactivate-user',
    DeactivateWorkspace: 'deactivate-workspace',
    DeleteBankDetails: 'delete-bank-details',
    DeleteDocuments: 'delete-documents',
    DeletePermissions: 'delete-permissions',
    DeleteTitles: 'delete-titles',
    DeleteUsers: 'delete-users',
    EditBankDetails: 'edit-bank-details',
    EditClients: 'edit-clients',
    EditDocuments: 'edit-documents',
    EditPermissions: 'edit-permissions',
    EditProfile: 'edit-profile',
    EditTeammates: 'edit-teammates',
    EditTitles: 'edit-titles',
    EditUsers: 'edit-users',
    EditWorkspace: 'edit-workspace',
    EditWorkspaceDetails: 'edit-workspace-details',
    EnableNewServices: 'enable-new-services',
    InviteUser: 'invite-user',
    LeaveWorkspace: 'leave-workspace',
    SetNotificationPreferences: 'set-notification-preferences',
    SetWorkspaceAsAgent: 'set-workspace-as-agent',
    TransferWorkspaceOwnership: 'transfer-workspace-ownership',
    VerifyClientRepresentation: 'verify-client-representation',
    ViewActivities: 'view-activities',
    ViewClients: 'view-clients',
    ViewDocuments: 'view-documents',
    ViewNotificationFeed: 'view-notification-feed',
    ViewPaymentStatements: 'view-payment-statements',
    ViewPermissions: 'view-permissions',
    ViewTeammates: 'view-teammates',
    ViewTitles: 'view-titles',
    ViewUsers: 'view-users',
    ViewWorkspace: 'view-workspace',
    ViewWorkspaceActivities: 'view-workspace-activities'
} as const;

export type PermissionEnum = typeof PermissionEnum[keyof typeof PermissionEnum];



