/* tslint:disable */
/* eslint-disable */
/**
 * Screenrights Permissions API
 * The Screenrights Permissions API documentation.
 *
 * The version of the OpenAPI document: 0.0.0-dev.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { UserTypeEnum } from './user-type-enum';

/**
 * 
 * @export
 * @interface UpdateUserDto
 */
export interface UpdateUserDto {
    /**
     * 
     * @type {UserTypeEnum}
     * @memberof UpdateUserDto
     */
    userType?: UserTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserDto
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserDto
     */
    middleName?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserDto
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserDto
     */
    emailAddress?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserDto
     */
    imageUri?: string;
}



