/* tslint:disable */
/* eslint-disable */
/**
 * Screenrights Permissions API
 * The Screenrights Permissions API documentation.
 *
 * The version of the OpenAPI document: 0.0.0-dev.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { UserTypeEnum } from './user-type-enum';

/**
 * 
 * @export
 * @interface UpdatePermissionDto
 */
export interface UpdatePermissionDto {
    /**
     * 
     * @type {UserTypeEnum}
     * @memberof UpdatePermissionDto
     */
    permissionType?: UserTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof UpdatePermissionDto
     */
    displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePermissionDto
     */
    section?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePermissionDto
     */
    description?: string;
}



