/* tslint:disable */
/* eslint-disable */
/**
 * Screenrights Permissions API
 * The Screenrights Permissions API documentation.
 *
 * The version of the OpenAPI document: 0.0.0-dev.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { RolePermissionDto } from './role-permission-dto';
// May contain unused imports in some cases
// @ts-ignore
import { UserTypeEnum } from './user-type-enum';

/**
 * 
 * @export
 * @interface UpdateRoleDto
 */
export interface UpdateRoleDto {
    /**
     * 
     * @type {UserTypeEnum}
     * @memberof UpdateRoleDto
     */
    roleType?: UserTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof UpdateRoleDto
     */
    displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateRoleDto
     */
    description?: string;
    /**
     * 
     * @type {Array<RolePermissionDto>}
     * @memberof UpdateRoleDto
     */
    permissions?: Array<RolePermissionDto>;
}



