/* tslint:disable */
/* eslint-disable */
/**
 * Screenrights Permissions API
 * The Screenrights Permissions API documentation.
 *
 * The version of the OpenAPI document: 0.0.0-dev.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { InvitationRoleEnum } from './invitation-role-enum';
// May contain unused imports in some cases
// @ts-ignore
import { InvitationStatusEnum } from './invitation-status-enum';
// May contain unused imports in some cases
// @ts-ignore
import { InvitationTemplateEnum } from './invitation-template-enum';

/**
 * 
 * @export
 * @interface UpdateInvitationDto
 */
export interface UpdateInvitationDto {
    /**
     * 
     * @type {InvitationTemplateEnum}
     * @memberof UpdateInvitationDto
     */
    invitationTemplate?: InvitationTemplateEnum;
    /**
     * 
     * @type {Array<InvitationRoleEnum>}
     * @memberof UpdateInvitationDto
     */
    userRoles?: Array<InvitationRoleEnum>;
    /**
     * 
     * @type {InvitationStatusEnum}
     * @memberof UpdateInvitationDto
     */
    invitationStatus?: InvitationStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof UpdateInvitationDto
     */
    inviteeName?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateInvitationDto
     */
    emailAddress?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateInvitationDto
     */
    inviter?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateInvitationDto
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateInvitationDto
     */
    workspaceName?: string;
}



